"""empty message

Revision ID: 2a006fa06649
Revises: 4eaa692b46c2
Create Date: 2019-07-26 21:16:57.148299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a006fa06649'
down_revision = '4eaa692b46c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_quota', sa.BigInteger))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_quota')
    # ### end Alembic commands ###
