#!/command/with-contenv sh
set -e

if test -z "$PUID" && test -z "$PGID"; then
    echo "Neither PUID or PGID are set, skipping permission changes."
    exit 0
fi

if test -n "$PUID"; then
    /usr/sbin/usermod -u "$PUID" "$APP_USER" > /dev/null
fi

if test -n "$PGID"; then
    /usr/sbin/groupmod -g "$PGID" "$APP_USER" > /dev/null
fi

chown -R "$APP_USER:$APP_USER" /config /data /app /static
