#!/command/with-contenv sh
set -e

cd /app || exit 1
. "$VENV_PATH/bin/activate"

if test -d "$PATHS_STATIC/.webassets-cache"; then
    s6-setuidgid "$APP_USER" flask assets clean
fi

s6-setuidgid "$APP_USER" flask assets build
