##
## Configuration can be done here or via env vars.
## Env var formatting is documented here: https://www.dynaconf.com/envvars/
## Env var prefix is set to 'CFG_' instead of 'DYNACONF_'.
##

# Site name
name = "pste"

# MUST be set to a secure, random value.
# Generate one with:
#    python -c "import uuid; print(uuid.uuid4().hex);"
secret_key = ""

# Database
# https://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
sqlalchemy_database_uri = ""

# Redis
# https://redis.readthedocs.io/en/stable/connections.html#redis.Redis.from_url
redis_url = ""

# Overrides redis_url specifically for sessions.
# sessions_redis_url = ""

# File extensions that will be displayed as plaintext regardless of the file's mimetype.
plaintext_types = [
    "txt",
    "php",
    "rb",
    "sh",
    "py",
    "conf",
    "c",
    "cpp",
    "java",
    "rs",
    "html",
    "htm",
    "js",
    "xml",
    "sql",
    "lua",
    "cs",
    "pl",
    "md",
    "ini",
    "shtml",
    "yaml",
    "cfg",
    "go",
    "fish",
    "yml",
    "bash",
]

# If disabled, users can only be created via 'flask user create'.
enable_registration = false

# Storage quota per-user in bytes. Default is 1GB
user_storage_limit = 1_073_741_824

# Max size of a single file upload. Default is 1GB.
max_upload_size = 1_073_741_824

# Minimum length of generated file URLs, excluding the file extension part (if any).
min_url_length = 5

# Sentry
# https://sentry.io
sentry_dsn = ""
