name: Lint

on: [workflow_call]

env:
  RUFF_OUTPUT_FORMAT: "github"
  RUFF_NO_CACHE: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        node-version: ["20"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Cache virtualenv
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        uses: pre-commit/action@v3.0.0
