name: Lint

on: [workflow_call]

env:
  RUFF_OUTPUT_FORMAT: 'github'
  RUFF_NO_CACHE: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        node-version: ['20']
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install Python dependencies
        run: poetry install --no-root

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        uses: pre-commit/action@v3.0.0
